services:
  api:
    build:
      context: .
      target: runner
    image: my-image:prod
    container_name: my-api-container
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: initial_password
    ports:
      - "5432:5432"